### ISSUE TITLE
Question: add()  -> callback

### ISSUE THREAD

**Issue by RobTillaart** [ripred/Smooth#1]
Nice library, written a similar proto-lib in the past (never published)

Question why is in the add() the callback of upper an >=  while that from lower is only <  (without the equal)?

**Comment by ripred** [comment]
That is in keeping with standard bounding semantics used most language grammars and API's I believe. Sincere Thanks for the interest!

**Comment by ripred** [comment]
reopen if needed

**Comment by RobTillaart** [comment]
OK, its by design 👍
