### ISSUE TITLE
Arduino build CI

### ISSUE THREAD

**Issue by RobTillaart** [ripred/Smooth#3]
@ripred 

I have for most of my libraries an Arduino build-CI in place. 
It compiles on a number of platforms and allows unit tests to be run. 
Furthermore a LINT action is in place
These tools/actions are also used by the Arduino library manager. 

Status is shown in badges in the readme.md
e.g. see https://github.com/RobTillaart/Statistic

If you are interested, I can make a PR to get this started.

**Comment by ripred** [comment]
you bet! Feel free. It would improve things and I'd love the chance to learn and add some new skills heh

**Comment by RobTillaart** [comment]
Created a PR 
- https://github.com/ripred/Smooth/pull/4  => you may need to allow to run the actions.
- add arduino build-CI
- fixed name one example name (detected by the build :)
- add some basic unit tests, which can be extended.
-

**Comment by ripred** [comment]
So great! Added you to the repo's collab list
