### ISSUE TITLE
Need Clarification about example in Readme.md

### ISSUE THREAD

**Issue by mlksahib** [ripred/Smooth#6]
In example code where you used snprintf() function, while printing 'sample' value you passed 'updown' variable as argument/reference. shouldn't it be 'sample' variable?
snprintf(scratch, sizeof(scratch), "count: %4d, **sample: %3d**, average: %3d\n",
        average.get_count(),
        **updown**,
        (int) average());                   // or call average.get_avg()

**Comment by mlksahib** [comment]
Thank you. Btw i'm new to arduino and a fan of your extensive work. Hats off

**Comment by RobTillaart** [comment]
Think this issue is solved, otherwise feel free to reopen.
